# Generated by Django 3.2.6 on 2021-08-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denj',
            name='location',
        ),
    ]
