# Generated by Django 3.2.6 on 2021-08-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denj', '0002_remove_denj_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denj',
            name='discoverer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='discoverer',
        ),
    ]
