# Generated by Django 3.2.6 on 2021-08-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denj', '0003_auto_20210810_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denj',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
