# Generated by Django 3.2.6 on 2021-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denj', '0005_auto_20210810_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denj',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
