# Generated by Django 3.2.6 on 2021-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denj', '0006_alter_denj_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denj',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
